[control_node]
# 本地控制节点
rhel-manager ansible_host=127.0.0.1 ansible_connection=local

[managed_nodes]
# 远程 Rocky 节点
rocky-node-01 ansible_host=192.168.112.136

[all:vars]
# 核心：使用普通用户以维持 Rootless 环境
ansible_user=danny
# 如果需要 root 权限（如装包、开防火墙），Ansible 会通过 become 处理
#ansible_become_pass=
